[2025-03-04T19:41:48.730+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T19:41:48.915+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training manual__2025-03-04T19:41:42.960366+00:00 [queued]>
[2025-03-04T19:41:48.956+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training manual__2025-03-04T19:41:42.960366+00:00 [queued]>
[2025-03-04T19:41:48.958+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-04T19:41:49.035+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_training> on 2025-03-04 19:41:42.960366+00:00
[2025-03-04T19:41:49.080+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=8742) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-04T19:41:49.084+0000] {standard_task_runner.py:72} INFO - Started process 8743 to run task
[2025-03-04T19:41:49.084+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_training', 'execute_training', 'manual__2025-03-04T19:41:42.960366+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_training_dag.py', '--cfg-path', '/tmp/tmphjwotkjj']
[2025-03-04T19:41:49.085+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask execute_training
[2025-03-04T19:41:49.275+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection_training.execute_training manual__2025-03-04T19:41:42.960366+00:00 [running]> on host b7f28f610775
[2025-03-04T19:41:49.533+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='datamasterylab.com' AIRFLOW_CTX_DAG_ID='fraud_detection_training' AIRFLOW_CTX_TASK_ID='execute_training' AIRFLOW_CTX_EXECUTION_DATE='2025-03-04T19:41:42.960366+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-04T19:41:42.960366+00:00'
[2025-03-04T19:41:49.534+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-04T19:41:53.355+0000] {warnings.py:112} WARNING - /opt/***/dags/fraud_detection_training.py:15: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  from numpy.array_api import astype

[2025-03-04T19:41:53.427+0000] {fraud_detection_training_dag.py:23} INFO - Initializing fraud detection training
[2025-03-04T19:41:53.433+0000] {fraud_detection_training.py:58} INFO - Configuration loaded successfully
[2025-03-04T19:41:53.539+0000] {fraud_detection_training.py:83} INFO - Minio connection verified. Buckets: ['mlflow']
[2025-03-04T19:41:53.713+0000] {fraud_detection_training.py:170} INFO - Starting model training process
[2025-03-04T19:41:53.713+0000] {fraud_detection_training.py:96} INFO - Connecting to kafka topic transactions
[2025-03-04T19:41:53.752+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=bootstrap-0 host=pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('18.169.210.18', 9092)]>: connecting to pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 [('18.169.210.18', 9092) IPv4]
[2025-03-04T19:41:53.755+0000] {conn.py:1219} INFO - Probing node bootstrap-0 broker version
[2025-03-04T19:41:53.767+0000] {conn.py:480} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=bootstrap-0 host=pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('18.169.210.18', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-03-04T19:41:53.976+0000] {conn.py:665} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=bootstrap-0 host=pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('18.169.210.18', 9092)]>: Authenticated as XGISOSVJLGK43N6I via PLAIN
[2025-03-04T19:41:53.977+0000] {conn.py:449} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=bootstrap-0 host=pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('18.169.210.18', 9092)]>: Connection complete.
[2025-03-04T19:41:54.109+0000] {conn.py:1282} INFO - Broker version identified as 2.6.0
[2025-03-04T19:41:54.111+0000] {conn.py:1283} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2025-03-04T19:41:54.115+0000] {consumer.py:118} WARNING - group_id is None: disabling auto-commit.
[2025-03-04T19:41:54.119+0000] {subscription_state.py:171} INFO - Updating subscribed topics to: ('transactions',)
[2025-03-04T19:41:54.131+0000] {subscription_state.py:257} INFO - Updated partition assignment: [('transactions', 0), ('transactions', 1), ('transactions', 2), ('transactions', 3), ('transactions', 4), ('transactions', 5)]
[2025-03-04T19:41:54.146+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=4 host=b4-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('18.135.141.220', 9092)]>: connecting to b4-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 [('18.135.141.220', 9092) IPv4]
[2025-03-04T19:41:54.252+0000] {conn.py:480} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=4 host=b4-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('18.135.141.220', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-03-04T19:41:54.720+0000] {conn.py:665} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=4 host=b4-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('18.135.141.220', 9092)]>: Authenticated as XGISOSVJLGK43N6I via PLAIN
[2025-03-04T19:41:54.723+0000] {conn.py:449} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=4 host=b4-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('18.135.141.220', 9092)]>: Connection complete.
[2025-03-04T19:41:54.726+0000] {conn.py:928} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=bootstrap-0 host=pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('18.169.210.18', 9092)]>: Closing connection. 
[2025-03-04T19:41:54.878+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=1 host=b1-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('18.169.76.35', 9092)]>: connecting to b1-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 [('18.169.76.35', 9092) IPv4]
[2025-03-04T19:41:54.985+0000] {conn.py:480} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=1 host=b1-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('18.169.76.35', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-03-04T19:41:55.428+0000] {conn.py:665} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=1 host=b1-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('18.169.76.35', 9092)]>: Authenticated as XGISOSVJLGK43N6I via PLAIN
[2025-03-04T19:41:55.430+0000] {conn.py:449} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=1 host=b1-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('18.169.76.35', 9092)]>: Connection complete.
[2025-03-04T19:41:55.587+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=2 host=b2-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('18.175.87.62', 9092)]>: connecting to b2-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 [('18.175.87.62', 9092) IPv4]
[2025-03-04T19:41:55.692+0000] {conn.py:480} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=2 host=b2-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('18.175.87.62', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-03-04T19:41:56.037+0000] {conn.py:665} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=2 host=b2-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('18.175.87.62', 9092)]>: Authenticated as XGISOSVJLGK43N6I via PLAIN
[2025-03-04T19:41:56.038+0000] {conn.py:449} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=2 host=b2-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('18.175.87.62', 9092)]>: Connection complete.
[2025-03-04T19:41:56.232+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=5 host=b5-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('3.11.137.161', 9092)]>: connecting to b5-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 [('3.11.137.161', 9092) IPv4]
[2025-03-04T19:41:56.339+0000] {conn.py:480} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=5 host=b5-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('3.11.137.161', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-03-04T19:41:56.818+0000] {conn.py:665} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=5 host=b5-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('3.11.137.161', 9092)]>: Authenticated as XGISOSVJLGK43N6I via PLAIN
[2025-03-04T19:41:56.819+0000] {conn.py:449} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=5 host=b5-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('3.11.137.161', 9092)]>: Connection complete.
[2025-03-04T19:41:56.947+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=3 host=b3-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('18.132.227.118', 9092)]>: connecting to b3-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 [('18.132.227.118', 9092) IPv4]
[2025-03-04T19:41:57.052+0000] {conn.py:480} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=3 host=b3-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('18.132.227.118', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-03-04T19:41:57.493+0000] {conn.py:665} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=3 host=b3-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('18.132.227.118', 9092)]>: Authenticated as XGISOSVJLGK43N6I via PLAIN
[2025-03-04T19:41:57.495+0000] {conn.py:449} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=3 host=b3-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('18.132.227.118', 9092)]>: Connection complete.
[2025-03-04T19:41:57.628+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=0 host=b0-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('3.11.225.156', 9092)]>: connecting to b0-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 [('3.11.225.156', 9092) IPv4]
[2025-03-04T19:41:57.732+0000] {conn.py:480} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=0 host=b0-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('3.11.225.156', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-03-04T19:41:58.164+0000] {conn.py:665} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=0 host=b0-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('3.11.225.156', 9092)]>: Authenticated as XGISOSVJLGK43N6I via PLAIN
[2025-03-04T19:41:58.166+0000] {conn.py:449} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=0 host=b0-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('3.11.225.156', 9092)]>: Connection complete.
[2025-03-04T19:42:12.742+0000] {conn.py:928} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=4 host=b4-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('18.135.141.220', 9092)]>: Closing connection. 
[2025-03-04T19:42:12.752+0000] {fetcher.py:782} INFO - Fetch to node 4 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.0.5, node_id=4 host=b4-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('18.135.141.220', 9092)]>
[2025-03-04T19:42:12.754+0000] {conn.py:928} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=1 host=b1-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('18.169.76.35', 9092)]>: Closing connection. 
[2025-03-04T19:42:12.756+0000] {fetcher.py:782} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.0.5, node_id=1 host=b1-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('18.169.76.35', 9092)]>
[2025-03-04T19:42:12.757+0000] {conn.py:928} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=2 host=b2-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('18.175.87.62', 9092)]>: Closing connection. 
[2025-03-04T19:42:12.758+0000] {fetcher.py:782} INFO - Fetch to node 2 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.0.5, node_id=2 host=b2-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('18.175.87.62', 9092)]>
[2025-03-04T19:42:12.760+0000] {conn.py:928} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=5 host=b5-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('3.11.137.161', 9092)]>: Closing connection. 
[2025-03-04T19:42:12.762+0000] {fetcher.py:782} INFO - Fetch to node 5 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.0.5, node_id=5 host=b5-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('3.11.137.161', 9092)]>
[2025-03-04T19:42:12.763+0000] {conn.py:928} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=3 host=b3-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('18.132.227.118', 9092)]>: Closing connection. 
[2025-03-04T19:42:12.766+0000] {fetcher.py:782} INFO - Fetch to node 3 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.0.5, node_id=3 host=b3-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('18.132.227.118', 9092)]>
[2025-03-04T19:42:12.767+0000] {conn.py:928} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=0 host=b0-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('3.11.225.156', 9092)]>: Closing connection. 
[2025-03-04T19:42:12.769+0000] {fetcher.py:782} INFO - Fetch to node 0 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.0.5, node_id=0 host=b0-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('3.11.225.156', 9092)]>
[2025-03-04T19:42:13.534+0000] {fraud_detection_training.py:124} INFO - Kafka data read successfully with fraud rate: 0.38%
[2025-03-04T19:42:21.680+0000] {logging_mixin.py:190} INFO - 🏃 View run funny-fowl-410 at: http://mlflow-server:5500/#/experiments/1/runs/a8c45241cba646edb539b37e9f805c73
[2025-03-04T19:42:21.681+0000] {logging_mixin.py:190} INFO - 🧪 View experiment at: http://mlflow-server:5500/#/experiments/1
[2025-03-04T19:42:21.724+0000] {fraud_detection_training.py:323} ERROR - Training failed: 'param'
Traceback (most recent call last):
  File "/opt/airflow/dags/fraud_detection_training.py", line 213, in train_model
    n_estimators=self.config['model']['param']['n_estimators'],
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'param'
[2025-03-04T19:42:21.727+0000] {fraud_detection_training_dag.py:29} ERROR - Training failed: 'param'
Traceback (most recent call last):
  File "/opt/airflow/dags/fraud_detection_training_dag.py", line 25, in _train_model
    model, precision = trainer.train_model()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fraud_detection_training.py", line 213, in train_model
    n_estimators=self.config['model']['param']['n_estimators'],
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'param'
[2025-03-04T19:42:21.781+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/fraud_detection_training_dag.py", line 25, in _train_model
    model, precision = trainer.train_model()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fraud_detection_training.py", line 213, in train_model
    n_estimators=self.config['model']['param']['n_estimators'],
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'param'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fraud_detection_training_dag.py", line 30, in _train_model
    raise AirflowException(f'Model training failed: {str(e)}')
airflow.exceptions.AirflowException: Model training failed: 'param'
[2025-03-04T19:42:21.787+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=fraud_detection_training, task_id=execute_training, run_id=manual__2025-03-04T19:41:42.960366+00:00, execution_date=20250304T194142, start_date=20250304T194148, end_date=20250304T194221
[2025-03-04T19:42:21.913+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-04T19:42:21.913+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task execute_training (Model training failed: 'param'; 8743)
Traceback (most recent call last):
  File "/opt/airflow/dags/fraud_detection_training_dag.py", line 25, in _train_model
    model, precision = trainer.train_model()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fraud_detection_training.py", line 213, in train_model
    n_estimators=self.config['model']['param']['n_estimators'],
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'param'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fraud_detection_training_dag.py", line 30, in _train_model
    raise AirflowException(f'Model training failed: {str(e)}')
airflow.exceptions.AirflowException: Model training failed: 'param'
[2025-03-04T19:42:21.969+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-04T19:42:22.055+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-04T19:42:22.063+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
